import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart' hide MenuItem;
import 'package:pawsome/model/language_model.dart';
import 'package:pawsome/model/menu_item.dart';
import 'package:pawsome/resources/language_manager.dart';
import 'package:pawsome/resources/strings_manager.dart';

String appVersion = '1.0';

List<BoxShadow> shadowList = [
  BoxShadow(
      color: Colors.grey.shade400, blurRadius: 30, offset: const Offset(0, 10))
];

List<String> animalClass = [
  AppStrings.bird.tr(),
  AppStrings.cat.tr(),
  AppStrings.dog.tr(),
  AppStrings.ferret.tr(),
  AppStrings.fish.tr(),
  AppStrings.guineaPig.tr(),
  AppStrings.horse.tr(),
  AppStrings.iguana.tr(),
  AppStrings.mouseRat.tr(),
  AppStrings.otter.tr(),
  AppStrings.rabbit.tr(),
  AppStrings.tortoise.tr(),
];

List<String> animalValueClass = [
  AppStrings.bird,
  AppStrings.cat,
  AppStrings.dog,
  AppStrings.ferret,
  AppStrings.fish,
  AppStrings.guineaPig,
  AppStrings.horse,
  AppStrings.iguana,
  AppStrings.mouseRat,
  AppStrings.otter,
  AppStrings.rabbit,
  AppStrings.tortoise,
];

List<String> birdValueSpecies = [
  AppStrings.unknown,
  AppStrings.africanGrayParrot,
  AppStrings.amazonParrot,
  AppStrings.blueHeadedParrot,
  AppStrings.bronzeWingedParrot,
  AppStrings.budgerigarBudgieParakeet,
  AppStrings.canary,
  AppStrings.cockatiel,
  AppStrings.cockatoo,
  AppStrings.dovePigeon,
  AppStrings.duskyPionus,
  AppStrings.eclectusParrot,
  AppStrings.finch,
  AppStrings.greenCheekedParakeet,
  AppStrings.hyacinthMacaw,
  AppStrings.loveBird,
  AppStrings.macaw,
  AppStrings.monkParakeet,
  AppStrings.redBilledPionus,
  AppStrings.scalyHeadedPionus,
  AppStrings.senegalParrot,
  AppStrings.sunParakeet,
  AppStrings.roseRingedParakeet,
  AppStrings.whiteCrownedPionus,
  AppStrings.zebraFinch,
];

List<String> catValueSpecies = [
  AppStrings.unknown,
  AppStrings.abyssinian,
  AppStrings.americanBobtail,
  AppStrings.americanCurl,
  AppStrings.americanShorthair,
  AppStrings.americanWirehair,
  AppStrings.bengalCat,
  AppStrings.birman,
  AppStrings.balineseCat,
  AppStrings.bombayCat,
  AppStrings.britishLonghair,
  AppStrings.britishShorthair,
  AppStrings.burmeseCat,
  AppStrings.burmilla,
  AppStrings.caracal,
  AppStrings.chartreux,
  AppStrings.cornishRex,
  AppStrings.cymric,
  AppStrings.donskoy,
  AppStrings.europeanShorthair,
  AppStrings.exoticShorthair,
  AppStrings.havanaBrown,
  AppStrings.himalayanCat,
  AppStrings.korat,
  AppStrings.laperm,
  AppStrings.lykoi,
  AppStrings.maineCoon,
  AppStrings.manxCat,
  AppStrings.munchkinCat,
  AppStrings.nebelung,
  AppStrings.norwegianForestCat,
  AppStrings.ocicat,
  AppStrings.orientalLonghair,
  AppStrings.orientalShorthair,
  AppStrings.persianCat,
  AppStrings.peterbald,
  AppStrings.ragamuffin,
  AppStrings.ragdoll,
  AppStrings.russianBlue,
  AppStrings.savannahCat,
  AppStrings.scottishFold,
  AppStrings.selkirkRex,
  AppStrings.siameseCat,
  AppStrings.siberianCat,
  AppStrings.singapuraCat,
  AppStrings.somaliCat,
  AppStrings.sphynxCat,
  AppStrings.thaiCat,
  AppStrings.tonkineseCat,
  AppStrings.toyger,
  AppStrings.turkishAngora,
  AppStrings.vanCat,
];

List<String> dogValueSpecies = [
  AppStrings.unknown,
  AppStrings.affenpinscher,
  AppStrings.afghanHound,
  AppStrings.airedaleTerrier,
  AppStrings.alaskanMalamute,
  AppStrings.americanBulldog,
  AppStrings.americanEskimoDog,
  AppStrings.americanStaffordshireTerrier,
  AppStrings.australianCattleDog,
  AppStrings.australianShepherd,
  AppStrings.basenji,
  AppStrings.bassetHound,
  AppStrings.beagle,
  AppStrings.beardedCollie,
  AppStrings.belgianShepherd,
  AppStrings.berneseMountainDog,
  AppStrings.bichonFrise,
  AppStrings.borderCollie,
  AppStrings.borderTerrier,
  AppStrings.bostonTerrier,
  AppStrings.boxer,
  AppStrings.brittany,
  AppStrings.brusselsGriffon,
  AppStrings.bulldog,
  AppStrings.bullTerrier,
  AppStrings.cairnTerrier,
  AppStrings.cavalierKingCharlesSpaniel,
  AppStrings.chihuahua,
  AppStrings.chowChow,
  AppStrings.dachshund,
  AppStrings.dalmation,
  AppStrings.dobermann,
  AppStrings.englishCockerSpaniel,
  AppStrings.frenchBulldog,
  AppStrings.germanShepherd,
  AppStrings.greatDane,
  AppStrings.goldenRetriever,
  AppStrings.irishSetter,
  AppStrings.labradorRetriever,
  AppStrings.malteseDog,
  AppStrings.newfoundlandDog,
  AppStrings.papillon,
  AppStrings.pembrokeWelshCorgi,
  AppStrings.pomeranian,
  AppStrings.poodle,
  AppStrings.pug,
  AppStrings.rottweiler,
  AppStrings.shetlandSheepdog,
  AppStrings.shihTzu,
  AppStrings.siberianHusky,
  AppStrings.softcoatedWheatenTerrier,
  AppStrings.yorkshireTerrier,
];

List<String> ferretValueSpecies = [
  AppStrings.unknown,
  AppStrings.albinoFerret,
  AppStrings.blazeFerret,
  AppStrings.champagneFerret,
  AppStrings.chocolateFerret,
  AppStrings.cinnamonFerret,
  AppStrings.dalmatianFerret,
  AppStrings.pandaFerret,
  AppStrings.siameseFerret,
  AppStrings.silverFerret,
];

List<String> fishValueSpecies = [
  AppStrings.unknown,
  AppStrings.africanCichlid,
  AppStrings.angelfish,
  AppStrings.asianStoneCatfish,
  AppStrings.bichir,
  AppStrings.bloodfinTetra,
  AppStrings.bloodParrotCichlid,
  AppStrings.cardinalTetra,
  AppStrings.cherryBarb,
  AppStrings.cherryShrimp,
  AppStrings.clownLoach,
  AppStrings.convictCichlid,
  AppStrings.danioMargaritatus,
  AppStrings.diamondTetra,
  AppStrings.dwarfGourami,
  AppStrings.firemouthCichlid,
  AppStrings.glassCatfish,
  AppStrings.goldBarb,
  AppStrings.goldfish,
  AppStrings.greenTexasCichlid,
  AppStrings.guppy,
  AppStrings.harlequinRasboras,
  AppStrings.jackDempsey,
  AppStrings.killifish,
  AppStrings.kuhliLoach,
  AppStrings.marbledHatchetfish,
  AppStrings.mollies,
  AppStrings.neonTetra,
  AppStrings.odessaBarb,
  AppStrings.oscarCichlid,
  AppStrings.otocinclus,
  AppStrings.pearlGourami,
  AppStrings.pictusCatfish,
  AppStrings.platy,
  AppStrings.rainbowfish,
  AppStrings.rainbowShark,
  AppStrings.ramCichlid,
  AppStrings.raphaelCatfish,
  AppStrings.redeyeTetra,
  AppStrings.rosyBarb,
  AppStrings.siameseFightingFish,
  AppStrings.swordTail,
  AppStrings.tigerBarb,
  AppStrings.upsideDownCatfish,
  AppStrings.whiteCloudMountainMinnow,
  AppStrings.zebrafish,
];

List<String> guineaPigValueSpecies = [
  AppStrings.unknown,
  AppStrings.abyssinianGuineaPig,
  AppStrings.americanGuineaPig,
  AppStrings.peruvianGuineaPig,
  AppStrings.rexGuineaPig,
  AppStrings.sheltieSilkieGuineaPig,
  AppStrings.skinnyGuineaPig,
  AppStrings.teddyGuineaPig,
  AppStrings.texelGuineaPig,
  AppStrings.whiteCrestedGuineaPig,
];

List<String> horseValueSpecies = [
  AppStrings.unknown,
  AppStrings.akhalTeke,
  AppStrings.americanPaintHorse,
  AppStrings.americanQuarterHorse,
  AppStrings.americanSaddlebred,
  AppStrings.andalusianHorse,
  AppStrings.appaloosa,
  AppStrings.arabianHorse,
  AppStrings.ardennais,
  AppStrings.belgianHorse,
  AppStrings.belgianWarmblood,
  AppStrings.blackForestHorse,
  AppStrings.bretonHorse,
  AppStrings.clydesdaleHorse,
  AppStrings.criolloHorse,
  AppStrings.curlyHorse,
  AppStrings.dutchWarmblood,
  AppStrings.falabella,
  AppStrings.fellPony,
  AppStrings.fjordHorse,
  AppStrings.friesianHorse,
  AppStrings.gypsyHorse,
  AppStrings.haflinger,
  AppStrings.hanoverianHorse,
  AppStrings.holsteiner,
  AppStrings.huculPony,
  AppStrings.icelandicHorse,
  AppStrings.irishSportHorse,
  AppStrings.knabstrupper,
  AppStrings.konik,
  AppStrings.lipizzan,
  AppStrings.lusitano,
  AppStrings.mangalargaMarchador,
  AppStrings.marwariHorse,
  AppStrings.missouriFoxTrotter,
  AppStrings.mongolianHorse,
  AppStrings.morganHorse,
  AppStrings.mustang,
  AppStrings.noriker,
  AppStrings.pasoFino,
  AppStrings.percheron,
  AppStrings.peruvianPaso,
  AppStrings.shetlandPony,
  AppStrings.shireHorse,
  AppStrings.silesianHorse,
  AppStrings.standardbred,
  AppStrings.tennesseeWalkingHorse,
  AppStrings.trakehner,
];

List<String> iguanaValueSpecies = [
  AppStrings.unknown,
  AppStrings.angelIslandChuckwalla,
  AppStrings.blueIguana,
  AppStrings.brachylophusBulabula,
  AppStrings.brachylophusFasciatus,
  AppStrings.commonChuckwalla,
  AppStrings.ctenosauraBakeri,
  AppStrings.ctenosauraFlavidorsalis,
  AppStrings.ctenosauraPalearis,
  AppStrings.ctenosauraPectinata,
  AppStrings.ctenosauraQuinquecarinata,
  AppStrings.cycluraNubila,
  AppStrings.desertIguana,
  AppStrings.fijiCrestedIguana,
  AppStrings.greenIguana,
  AppStrings.lesserAntilleanIguana,
  AppStrings.northernBahamianRockIguana,
  AppStrings.rhinocerosIguana,
  AppStrings.yucatanSpinyTailedIguana,
];

List<String> mouseRatValueSpecies = [
  AppStrings.unknown,
  AppStrings.africanPygmyMouse,
  AppStrings.blackRat,
  AppStrings.brownRat,
  AppStrings.cairoSpinyMouse,
  AppStrings.ceylonSpinyMouse,
  AppStrings.creteSpinyMouse,
  AppStrings.gairdnersShrewmouse,
  AppStrings.gambianPouchedRat,
  AppStrings.houseMouse,
  AppStrings.macedonianMouse,
  AppStrings.mattheysMouse,
  AppStrings.mongolianGerbil,
  AppStrings.natalMultimammateMouse,
  AppStrings.summitRat,
  AppStrings.temmincksMouse,
  AppStrings.turkestanRat,
];

List<String> otterValueSpecies = [
  AppStrings.unknown,
  AppStrings.africanClawlessOtter,
  AppStrings.americanMink,
  AppStrings.asianSmallClawedOtter,
  AppStrings.eurasianOtter,
  AppStrings.giantOtter,
  AppStrings.hairyNosedOtter,
  AppStrings.marineOtter,
  AppStrings.neotropicalOtter,
  AppStrings.northAmericanRiverOtter,
  AppStrings.seaOtter,
  AppStrings.smoothCoatedOtter,
  AppStrings.southernRiverOtter,
  AppStrings.spottedNeckedOtter,
];

List<String> rabbitValueSpecies = [
  AppStrings.unknown,
  AppStrings.alaskaRabbit,
  AppStrings.americanFuzzyLop,
  AppStrings.americanRabbit,
  AppStrings.annamiteStripedRabbit,
  AppStrings.appalachianCottontail,
  AppStrings.brushRabbit,
  AppStrings.bunyoroRabbit,
  AppStrings.cashmereLop,
  AppStrings.checkeredGiantRabbit,
  AppStrings.commonTapeti,
  AppStrings.deilenaar,
  AppStrings.desertCottontail,
  AppStrings.dicesCottontail,
  AppStrings.easternCottontail,
  AppStrings.europeanRabbit,
  AppStrings.flemishGiantRabbit,
  AppStrings.floridaWhiteRabbit,
  AppStrings.hollandLop,
  AppStrings.jerseyWooly,
  AppStrings.marshRabbit,
  AppStrings.mexicanCottontail,
  AppStrings.miniLop,
  AppStrings.mountainCottontail,
  AppStrings.netherlandDwarfRabbit,
  AppStrings.newEnglandCottontail,
  AppStrings.omiltemeCottontail,
  AppStrings.polishRabbit,
  AppStrings.pygmyRabbit,
  AppStrings.riverineRabbit,
  AppStrings.sumatranStripedRabbit,
  AppStrings.swampRabbit,
  AppStrings.tresMariasCottontail,
  AppStrings.volcanoRabbit,
];

List<String> tortoiseValueSpecies = [
  AppStrings.unknown,
  AppStrings.africanSpurredTortoise,
  AppStrings.aldabraGiantTortoise,
  AppStrings.asianForestTortoise,
  AppStrings.bellsHingeBackTortoise,
  AppStrings.bolsonTortoise,
  AppStrings.burmeseStarTortoise,
  AppStrings.chacoTortoise,
  AppStrings.egyptianTortoise,
  AppStrings.greekTortoise,
  AppStrings.hermannsTortoise,
  AppStrings.homesHingeBackTortoise,
  AppStrings.homopusAreolatus,
  AppStrings.homopusFemoralis,
  AppStrings.impressedTortoise,
  AppStrings.indianStarTortoise,
  AppStrings.leopardTortoise,
  AppStrings.marginatedTortoise,
  AppStrings.pancakeTortoise,
  AppStrings.ploughshareTortoise,
  AppStrings.radiatedTortoise,
  AppStrings.redFootedTortoise,
  AppStrings.russianTortoise,
  AppStrings.speckledCapeTortoise,
  AppStrings.spiderTortoise,
  AppStrings.texasTortoise,
  AppStrings.yellowFootedTortoise,
];

List<Map> categories = [
  {
    "name": AppStrings.birds.tr(),
    "value": 'Bird',
    "imagePath": 'assets/images/bird.png',
    "borderColor": const Color.fromRGBO(225, 226, 236, 1.0),
    "boxColor": const Color.fromRGBO(225, 226, 236, 1.0)
  },
  {
    "name": AppStrings.cats.tr(),
    "value": 'Cat',
    "imagePath": 'assets/images/cat.png',
    "borderColor": const Color.fromRGBO(240, 247, 204, 1.0),
    "boxColor": const Color.fromRGBO(240, 247, 204, 1.0)
  },
  {
    "name": AppStrings.dogs.tr(),
    "value": 'Dog',
    "imagePath": 'assets/images/dog.png',
    "borderColor": const Color.fromRGBO(254, 220, 110, 1.0),
    "boxColor": const Color.fromRGBO(246, 239, 212, 1.0)
  },
  {
    "name": AppStrings.ferrets.tr(),
    "value": 'Ferret',
    "imagePath": 'assets/images/ferret.png',
    "borderColor": const Color.fromRGBO(250, 177, 160, 1.0),
    "boxColor": const Color.fromRGBO(250, 177, 160, 1.0)
  },
  {
    "name": AppStrings.fishes.tr(),
    "value": 'Fish',
    "imagePath": 'assets/images/fish.png',
    "borderColor": const Color.fromRGBO(250, 177, 160, 1.0),
    "boxColor": const Color.fromRGBO(250, 177, 160, 1.0)
  },
  {
    "name": AppStrings.guineaPigs.tr(),
    "value": 'Guinea Pig',
    "imagePath": 'assets/images/guineaPig.png',
    "borderColor": const Color.fromRGBO(250, 177, 160, 1.0),
    "boxColor": const Color.fromRGBO(250, 177, 160, 1.0)
  },
  {
    "name": AppStrings.horses.tr(),
    "value": 'Horse',
    "imagePath": 'assets/images/horse.png',
    "borderColor": const Color.fromRGBO(129, 236, 236, 1.0),
    "boxColor": const Color.fromRGBO(129, 236, 236, 1.0)
  },
  {
    "name": AppStrings.iguanas.tr(),
    "value": 'Iguana',
    "imagePath": 'assets/images/iguana.png',
    "borderColor": const Color.fromRGBO(129, 236, 236, 1.0),
    "boxColor": const Color.fromRGBO(129, 236, 236, 1.0)
  },
  {
    "name": AppStrings.miceRats.tr(),
    "value": 'Mouse/Rat',
    "imagePath": 'assets/images/mouseRat.png',
    "borderColor": const Color.fromRGBO(129, 236, 236, 1.0),
    "boxColor": const Color.fromRGBO(129, 236, 236, 1.0)
  },
  {
    "name": AppStrings.otters.tr(),
    "value": 'Otter',
    "imagePath": 'assets/images/otter.png',
    "borderColor": const Color.fromRGBO(178, 190, 195, 1.0),
    "boxColor": const Color.fromRGBO(223, 230, 233, 1.0)
  },
  {
    "name": AppStrings.rabbits.tr(),
    "value": 'Rabbit',
    "imagePath": 'assets/images/rabbit.png',
    "borderColor": const Color.fromRGBO(195, 233, 243, 1.0),
    "boxColor": const Color.fromRGBO(195, 233, 243, 1.0)
  },
  {
    "name": AppStrings.tortoises.tr(),
    "value": 'Tortoise',
    "imagePath": 'assets/images/tortoise.png',
    "borderColor": const Color.fromRGBO(195, 233, 243, 1.0),
    "boxColor": const Color.fromRGBO(195, 233, 243, 1.0)
  },
];

final List<LanguageModel> languageList = [
  LanguageModel(Language.chinese, '中文', CHINESE_LOCAL),
  LanguageModel(Language.english, 'English', ENGLISH_LOCAL),
];

class MenuItems {
  static const adoption = MenuItem(AppStrings.Adoption, Icons.pets_rounded);
  // static const petStore = MenuItem('Pet Store', Icons.store_rounded);
  // static const veterinaryClinic =
  //     MenuItem('Veterinary Clinic', Icons.medical_services);
  static const myPets = MenuItem(AppStrings.myPets, Icons.favorite_rounded);
  static const petGallery =
      MenuItem(AppStrings.petGallery, Icons.photo_size_select_actual_outlined);
  static const petMap = MenuItem(AppStrings.petMap, Icons.location_on_rounded);
  static const messages = MenuItem(AppStrings.messages, Icons.mail_rounded);
  static const settings = MenuItem(AppStrings.settings, Icons.settings);
  static const all = [
    adoption,
    // petStore,
    // veterinaryClinic,
    myPets,
    petGallery,
    petMap,
    messages,
    settings,
  ];
}
